spring:
  datasource:
    password: 'root'
    url: jdbc:mysql://localhost:3307/fornecedor?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
